<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6483f736902c11ee3a970ff08d8b5c9d
{
    public static $files = array (
        '536316a08db3d840f2ffee3f1fc26715' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Includes/helpers.php',
    );

    public static $prefixLengthsPsr4 = array (
        'E' => 
        array (
            'EasyWhiteLabel\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'EasyWhiteLabel\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/EasyWhiteLabel',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'EasyWhiteLabel\\Activate' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Activate.php',
        'EasyWhiteLabel\\Admin\\AbstractAdminCore' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Admin/AbstractAdminCore.php',
        'EasyWhiteLabel\\Admin\\AdminCoreInterface' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Admin/AdminCoreInterface.php',
        'EasyWhiteLabel\\Admin\\AdminPageFactory' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Admin/AdminPageFactory.php',
        'EasyWhiteLabel\\Admin\\Form' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Admin/Form.php',
        'EasyWhiteLabel\\Admin\\Form\\Traits\\Element\\CategoryList' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Admin/Form/Traits/Element/CategoryList.php',
        'EasyWhiteLabel\\Admin\\Form\\Traits\\Element\\DataList' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Admin/Form/Traits/Element/DataList.php',
        'EasyWhiteLabel\\Admin\\Form\\Traits\\Element\\Image' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Admin/Form/Traits/Element/Image.php',
        'EasyWhiteLabel\\Admin\\Form\\Traits\\Element\\Input' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Admin/Form/Traits/Element/Input.php',
        'EasyWhiteLabel\\Admin\\Form\\Traits\\Element\\Nonce' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Admin/Form/Traits/Element/Nonce.php',
        'EasyWhiteLabel\\Admin\\Form\\Traits\\Element\\Select' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Admin/Form/Traits/Element/Select.php',
        'EasyWhiteLabel\\Admin\\Form\\Traits\\Element\\TextArea' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Admin/Form/Traits/Element/TextArea.php',
        'EasyWhiteLabel\\Admin\\OptionSettings' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Admin/OptionSettings.php',
        'EasyWhiteLabel\\Admin\\PageInterface' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Admin/PageInterface.php',
        'EasyWhiteLabel\\Admin\\Pages\\BackgroundPage' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Admin/Pages/BackgroundPage.php',
        'EasyWhiteLabel\\Admin\\Pages\\SettingsPage' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Admin/Pages/SettingsPage.php',
        'EasyWhiteLabel\\Admin\\Validate' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Admin/Validate.php',
        'EasyWhiteLabel\\Admin\\WhiteLabelAdmin' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Admin/WhiteLabelAdmin.php',
        'EasyWhiteLabel\\Customize\\CustomizerPanel' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Customize/CustomizerPanel.php',
        'EasyWhiteLabel\\Customize\\Settings\\Background' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Customize/Settings/Background.php',
        'EasyWhiteLabel\\Customize\\Settings\\Button' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Customize/Settings/Button.php',
        'EasyWhiteLabel\\Customize\\Settings\\Css' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Customize/Settings/Css.php',
        'EasyWhiteLabel\\Customize\\Settings\\Footer' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Customize/Settings/Footer.php',
        'EasyWhiteLabel\\Customize\\Settings\\Form' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Customize/Settings/Form.php',
        'EasyWhiteLabel\\Customize\\Settings\\Header' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Customize/Settings/Header.php',
        'EasyWhiteLabel\\Customize\\Settings\\Layout' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Customize/Settings/Layout.php',
        'EasyWhiteLabel\\Customize\\Settings\\Links' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Customize/Settings/Links.php',
        'EasyWhiteLabel\\Customize\\Settings\\Login' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Customize/Settings/Login.php',
        'EasyWhiteLabel\\Customize\\Settings\\Logo' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Customize/Settings/Logo.php',
        'EasyWhiteLabel\\Customize\\Settings\\Menu' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Customize/Settings/Menu.php',
        'EasyWhiteLabel\\Customize\\Settings\\SettingInterface' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Customize/Settings/SettingInterface.php',
        'EasyWhiteLabel\\DailyTask' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/DailyTask.php',
        'EasyWhiteLabel\\Lang' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Lang.php',
        'EasyWhiteLabel\\Lib\\ConnektInstaller' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Lib/ConnektInstaller.php',
        'EasyWhiteLabel\\Login\\AbstractSettings' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Login/AbstractSettings.php',
        'EasyWhiteLabel\\Login\\Background' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Login/Background.php',
        'EasyWhiteLabel\\Login\\Footer' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Login/Footer.php',
        'EasyWhiteLabel\\Login\\Header' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Login/Header.php',
        'EasyWhiteLabel\\Login\\Logo' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Login/Logo.php',
        'EasyWhiteLabel\\Login\\Style' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Login/Style.php',
        'EasyWhiteLabel\\PageAccess' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/PageAccess.php',
        'EasyWhiteLabel\\Plugin' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Plugin.php',
        'EasyWhiteLabel\\PluginInterface' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/PluginInterface.php',
        'EasyWhiteLabel\\Traits\\Singleton' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Traits/Singleton.php',
        'EasyWhiteLabel\\Transient' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/Transient.php',
        'EasyWhiteLabel\\UsefulPlugins\\Installer' => __DIR__ . '/../..' . '/src/EasyWhiteLabel/UsefulPlugins/Installer.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6483f736902c11ee3a970ff08d8b5c9d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6483f736902c11ee3a970ff08d8b5c9d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit6483f736902c11ee3a970ff08d8b5c9d::$classMap;

        }, null, ClassLoader::class);
    }
}
