<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    '536316a08db3d840f2ffee3f1fc26715' => $baseDir . '/src/EasyWhiteLabel/Includes/helpers.php',
);
