# DISABLED 
name: .org Deploy

env:
  SLUG: "shortcode-options"

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  tag:
    name: New Plugin .org release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          ini-values: display_errors = on, error_reporting = E_ALL
          tools: composer

      - name: Node Build 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: npm install

      - name: Install composer packages
        run: composer build

      - name: 🚀 Deploy WordPress Plugin
        uses: 10up/action-wordpress-plugin-deploy@develop
        env:
            SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
            SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
            SLUG: shortcode-options
            BUILD_DIR: ./build/trunk/
            INPUT_DRY_RUN: false
            # VERSION: 10012 # only for testing
