name: PHP Compatibility
on:
  pull_request:
  workflow_dispatch:

jobs:
  php-compatibility-test:
    name: PHP minimum 7.4
    runs-on: ubuntu-latest

    steps:
      - name: "📥 Checkout Repository Contents"
        uses: actions/checkout@v2

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          ini-values: display_errors = on, error_reporting = E_ALL
          tools: composer

      - name: 💽 Install dependencies
        run: composer install

      - name: 🧪 Run PHP Compatibility
        run: vendor/bin/phpcs white-label-login.php src/ --standard=PHPCompatibilityWP --extensions=php --runtime-set testVersion 7.4-
